apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentiment-deployment
  labels:
    app: sentimentclassifier
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sentimentclassifier
  template:
    metadata:
      labels:
        app: sentimentclassifier
    spec:
      containers:
      - name: sentclass
        image: ...
        ports:
        - containerPort: 80
